### ISSUE TITLE
Asset references not showing

### ISSUE THREAD

**Issue by lorenblue** [giantparticlegames/InspectorGraph#13]
Hi,

InspectorGraph appears to not be working properly on 2022.3.5 (not sure what other versions are affected). No references are shown for any asset.

![image](https://github.com/giantparticlegames/InspectorGraph/assets/40008150/b099c554-b9c9-4efb-b090-d9b63cb9519a)

**Comment by juanssl** [comment]
This is not an issue as discussed privately. This is a confusion about the functionality that the tool provides.
To clarify, the Inspector Graph currently does not show references from Assets to the inspected object, instead, it shows references from the inspected object to other objects.
