### ISSUE TITLE
Performance problems with Sprite Atlas

### ISSUE THREAD

**Issue by dragoon012234** [giantparticlegames/InspectorGraph#2]
Hi giantparticlegames. I used your tool, it's great, thanks for it.

I found that in a project that uses Sprite Atlas, the sprite will have one reference to the atlas and the atlas will also have multiple references to other sprites. When using InspectorGraph with an object with that sprite type, it will display all the sprites referenced by the atlas. It causes major performance problems. And I think it is not necessary to show sprites referenced by atlas.

I think it should avoid finding the reference if it is an atlas.

For anyone having this problem, you can add this `Assets\GiantParticleGames\InspectorGraph\Editor\InspectorGraph\Data\Nodes\ReferenceNodeFactory.cs`
```csharp
private void ProcessSerializedObject(ObjectNode parentNode, SerializedObject serializedObject, HashSet<Object> internalReferences = null)
{
    // Avoid Atlas
    if (parentNode.Target is UnityEngine.U2D.SpriteAtlas) return;
    // Scan direct references
    ...
}
```

Best regards.

**Comment by juanssl** [comment]
Hi @dragoon012234 

Thanks for reporting this issue and glad you like the tool.
We are currently working on a solution that fits this use case, others similar use cases and reduces the chances of encountering performance issues.

I'll update this thread with any updates.

**Comment by juanssl** [comment]
@dragoon012234 
Thanks again for your feedback.
The changes that fix this issue are merged to the [development](https://github.com/giantparticlegames/InspectorGraph/tree/development) branch and a new version of the package has been submitted to the Unity Asset Store. Once the submission is approved the changes will be merged to [main](https://github.com/giantparticlegames/InspectorGraph/tree/main).

**Comment by juanssl** [comment]
Version 0.9.0-b released with fix.
Closing issue.
