### ISSUE TITLE
Cannot Zoom +/- with mouse wheel

### ISSUE THREAD

**Issue by alex534488** [giantparticlegames/InspectorGraph#22]
Mouse wheel doesn't work. To zoom in or out you have to manually use the slider.

**Comment by juanssl** [comment]
Hey @alex534488 
That feature is available in the [Inspector Graph Pro](https://assetstore.unity.com/packages/tools/utilities/inspector-graph-pro-270005), by pressing [Alt on PC / Option on Mac] + Scroll Wheel
